clear; clc; close all;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Baseline: alpha=1/3, beta=.99, rho=.9, delta=.025, theta=1.5,

fontS=8;


load GRiskGHH2RCNfoc_2024_04_04_19_38-8k51.mat;

sigmavect'
alpha
beta
delta
rho
theta
A

S_SDZt1=S_SDZ;
S_CSDt1=S_CSD;
S_KSDt1=S_KSD;
S_ISDt1=S_ISD;
S_YSDt1=S_YSD;
S_NSDt1=S_NSD;
S_V1t1=S_V1;
S_V3t1=S_V3;
S_CBARt1=S_CBAR;
S_KBARt1=S_KBAR;
S_IBARt1=S_IBAR;
S_YBARt1=S_YBAR;
S_NBARt1=S_NBAR;
clear S_SDZ S_CSD S_KSD S_ISD S_YSD S_NSD S_V1 S_V3 S_CBAR S_KBAR S_IBAR S_YBAR S_NBAR;



load GRiskGHH2RCNfoc_2024_04_08_12_27-8k51b.mat;

sigmavect'
alpha
beta
delta
rho
theta
A

S_SDZt2=S_SDZ;
S_CSDt2=S_CSD;
S_KSDt2=S_KSD;
S_ISDt2=S_ISD;
S_YSDt2=S_YSD;
S_NSDt2=S_NSD;
S_V1t2=S_V1;
S_V3t2=S_V3;
S_CBARt2=S_CBAR;
S_KBARt2=S_KBAR;
S_IBARt2=S_IBAR;
S_YBARt2=S_YBAR;
S_NBARt2=S_NBAR;
clear S_SDZ S_V1 S_V3 S_KBAR S_YBAR S_CBAR S_NBAR;






S_SDZ=nan(1,9,6);
S_V1=nan(1,9,6);
S_V3=nan(1,9,6);
S_KBAR=nan(1,9,6);
S_YBAR=nan(1,9,6);
S_CBAR=nan(1,9,6);
S_NBAR=nan(1,9,6);

for i=1:6
    for j=1:5
        S_SDZ(:,2*(j-1)+1,i)=S_SDZt1(:,j,i);
        S_CSD(:,2*(j-1)+1,i)=S_CSDt1(:,j,i);
        S_KSD(:,2*(j-1)+1,i)=S_KSDt1(:,j,i);
        S_ISD(:,2*(j-1)+1,i)=S_ISDt1(:,j,i);
        S_YSD(:,2*(j-1)+1,i)=S_YSDt1(:,j,i);
        S_NSD(:,2*(j-1)+1,i)=S_NSDt1(:,j,i);
        S_V1(:,2*(j-1)+1,i)=S_V1t1(:,j,i);
        S_V3(:,2*(j-1)+1,i)=S_V3t1(:,j,i);
        S_CBAR(:,2*(j-1)+1,i)=S_CBARt1(:,j,i);
        S_KBAR(:,2*(j-1)+1,i)=S_KBARt1(:,j,i);
        S_IBAR(:,2*(j-1)+1,i)=S_IBARt1(:,j,i);
        S_YBAR(:,2*(j-1)+1,i)=S_YBARt1(:,j,i);
        S_NBAR(:,2*(j-1)+1,i)=S_NBARt1(:,j,i);
    end
    for j=1:4
        S_SDZ(:,2*j,i)=S_SDZt2(:,j,i);
        S_CSD(:,2*j,i)=S_CSDt2(:,j,i);
        S_KSD(:,2*j,i)=S_KSDt2(:,j,i);
        S_ISD(:,2*j,i)=S_ISDt2(:,j,i);
        S_YSD(:,2*j,i)=S_YSDt2(:,j,i);
        S_NSD(:,2*j,i)=S_NSDt2(:,j,i);
        S_V1(:,2*j,i)=S_V1t2(:,j,i);
        S_V3(:,2*j,i)=S_V3t2(:,j,i);
        S_CBAR(:,2*j,i)=S_CBARt2(:,j,i);
        S_KBAR(:,2*j,i)=S_KBARt2(:,j,i);
        S_IBAR(:,2*j,i)=S_IBARt2(:,j,i);
        S_YBAR(:,2*j,i)=S_YBARt2(:,j,i);
        S_NBAR(:,2*j,i)=S_NBARt2(:,j,i);
    end
end



sigmavect=[4; 3; 2; 1.01; .5; 0];
labels={[char(949) '=4']; [char(949) '=3']; [char(949) '=2']; [char(949) '=1']; [char(949) '=.5']; [char(949) '=0']};
colors={[0.6859 0.4035 0.2412]; [0.2941 0.5447 0.7494]; [0.3718 0.7176 0.3612]; [0.8650 0.8110 0.4330]; [1.0000 0.5482 0.1000]; [0.9047 0.1918 0.1988]; [0 0 1]; [0 0 1]}; % colors generated by linspecer.m



lsdzvect = length(S_SDZ);
lsigmavect = length(sigmavect);




% CSD=nan(lsdzvect,lsigmavect)
% for i=1:lsdzvect
%     for j=1:lsigmavect
%         CSD(i,j)=S_CSD(:,i,j)/S_CBAR(:,i,j)*100;
%     end
% end
% figure
% hold on;
% for i=1:lsdzvect-1
%     plot(sigmavect(:), CSD(i,:), 'color',colors{i,1},'linewidth',1.5);
%     %text(S_SDZ(:,1,i)*1.01, S_CSD(:,1,i)./S_CBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 4 -.15 24]);
% %ytickformat('%.1f')
% xlabel('\epsilon','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% legend(labels, 'Position', [.42 .2 .07 .3],'FontSize',fontS+2)
% title('Consumption SD/AVG','Interpreter','Latex','FontSize',fontS+4);
% hold off;







figure('Renderer', 'painters', 'Position', [0 1000 625 800]);
tiledlayout(3,2,'TileSpacing','compact','Padding','compact');

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), S_CSD(:,:,i)./S_CBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
    %text(S_SDZ(:,1,i)*1.01, S_CSD(:,1,i)./S_CBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.001 .1 -.15 22]);
%ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
%legend(labels, 'Position', [.42 .2 .07 .3],'FontSize',fontS+2)
title('Consumption SD/AVG','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), S_NSD(:,:,i)./S_NBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
    text(S_SDZ(:,1,i)*1.01, S_NSD(:,1,i)./S_NBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.001 .1 -.15 18]);
%ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
%legend(labels, 'Location','northwest','FontSize',fontS+2)
title('Labor  SD/AVG','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), S_KSD(:,:,i)./S_KBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
    text(S_SDZ(:,1,i)*1.01, S_KSD(:,1,i)./S_KBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.001 .1 -.2 33]);
%ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
%legend(labels, 'Location','northwest','FontSize',fontS+2)
title('Capital  SD/AVG','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), S_YSD(:,:,i)./S_YBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
    text(S_SDZ(:,1,i)*1.01, S_YSD(:,1,i)./S_YBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.001 .1 -.15 29]);
%ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
%legend(labels, 'Position', [.48 .35 .07 .15],'FontSize',fontS+2)
title('GDP SD/AVG','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), S_ISD(:,:,i)./S_IBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
    %text(S_SDZ(:,1,i)*1.01, S_ISD(:,1,i)./S_IBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.001 .1 -.3 43]);
%ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
legend(labels, 'Position', [.6 .15 .1 .12],'FontSize',fontS+4)
title('Investment  SD/AVG','Interpreter','Latex','FontSize',fontS+4);
hold off;

exportgraphics(gcf,"GRiskRBCepsilonGHH2rSD.eps","Resolution",300)




% figure('Renderer', 'painters', 'Position', [400 400 1000 400]);
% tiledlayout(1,2,'TileSpacing','compact');
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), S_CSD(:,:,i)./S_CBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
%     %text(S_SDZ(:,1,i)*1.01, S_CSD(:,1,i)./S_CBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .1 -.15 24]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% legend(labels, 'Position', [.42 .2 .07 .3],'FontSize',fontS+2)
% title('Consumption SD/AVG','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), S_NSD(:,:,i)./S_NBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
%     text(S_SDZ(:,1,i)*1.01, S_NSD(:,1,i)./S_NBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .1 -.15 19]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% %legend(labels, 'Location','northwest','FontSize',fontS+2)
% title('Labor  SD/AVG','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% exportgraphics(gcf,"GRiskRBCepsilonGHH2rSDcn.eps","Resolution",300)




% figure('Renderer', 'painters', 'Position', [400 400 1000 400]);
% tiledlayout(1,2,'TileSpacing','compact');
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), S_CSD(:,:,i)/cssTh*100, 'color',colors{i,1},'linewidth',1.5);
%     %text(S_SDZ(:,1,i)*1.01, S_CSD(:,1,i)/cssTh*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .1 -.15 24]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% legend(labels, 'Position', [.42 .2 .07 .3],'FontSize',fontS+2)
% title('Consumption SD/SS','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), S_NSD(:,:,i)/nssTh*100, 'color',colors{i,1},'linewidth',1.5);
%     text(S_SDZ(:,1,i)*1.01, S_NSD(:,1,i)/nssTh*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .1 -.15 19]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% %legend(labels, 'Location','northwest','FontSize',fontS+2)
% title('Labor SD/SS','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% exportgraphics(gcf,"GRiskRBCepsilonGHH2SDcn.eps","Resolution",300)




% figure('Renderer', 'painters', 'Position', [400 400 1000 800]);
% tiledlayout(2,2,'TileSpacing','compact');
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), S_ISD(:,:,i)./S_IBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
%     %text(S_SDZ(:,1,i)*1.01, S_ISD(:,1,i)./S_IBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .1 -.3 43]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% %legend(labels, 'Location','southeast','FontSize',fontS+2)
% title('Investment  SD/AVG','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), S_KSD(:,:,i)./S_KBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
%     text(S_SDZ(:,1,i)*1.01, S_KSD(:,1,i)./S_KBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .1 -.2 33]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% %legend(labels, 'Location','northwest','FontSize',fontS+2)
% title('Capital  SD/AVG','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), S_YSD(:,:,i)./S_YBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
%     %text(S_SDZ(:,1,i)*1.01, S_YSD(:,1,i)./S_YBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .1 -.15 34.5]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% legend(labels, 'Position', [.48 .35 .07 .15],'FontSize',fontS+2)
% title('GDP SD/AVG','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% exportgraphics(gcf,"GRiskRBCepsilonGHH2rSDiky.eps","Resolution",300)




figure('Renderer', 'painters', 'Position', [0 1000 625 800]);
tiledlayout(3,2,'TileSpacing','compact','Padding','compact');

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), (S_CBAR(:,:,i)/S_CBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
    text(S_SDZ(:,1,i)*1.01, (S_CBAR(:,1,i)/S_CBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.0015 .1 -.05 8.8]);
%ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
title('Consumption AVG/SS','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), (S_NBAR(:,:,i)/S_NBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
    text(S_SDZ(:,1,i)*1.01, (S_NBAR(:,1,i)/S_NBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.0015 .1 -.05 6.3]);
%ytickformat('%.0f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
%legend(labels, 'Location','northwest','FontSize',fontS+2)
title('Labor AVG/SS','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), (S_KBAR(:,:,i)/S_KBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
    text(S_SDZ(:,1,i)*1.01, (S_KBAR(:,1,i)/S_KBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.0015 .1 -.1 19]);
%ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
title('Capital and investment AVG/SS','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), (S_YBAR(:,:,i)/S_YBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
    text(S_SDZ(:,1,i)*1.01, (S_YBAR(:,1,i)/S_YBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.0015 .1 -.05 11.3]);
%ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
title('GDP AVG/SS','Interpreter','Latex','FontSize',fontS+4);
hold off;

S_ZBAR=S_YBAR./(A*S_KBAR.^alpha.*S_NBAR.^(1-alpha));
nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), (S_ZBAR(:,:,i)/S_ZBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
    %text(S_SDZ(:,1,i)*1.01, (S_ZBAR(:,1,i)/S_ZBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
for i=1:lsigmavect-1
    text(S_SDZ(:,1,i)*1.01, (S_ZBAR(:,1,i)/S_ZBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.0015 .1 -.005 1]);
ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
legend(labels, 'Position', [.6 .15 .1 .12],'FontSize',fontS+4)
title('TFP AVG/SS','Interpreter','Latex','FontSize',fontS+4);
hold off;

exportgraphics(gcf,"GRiskRBCepsilonGHH2M.eps","Resolution",300)





% figure('Renderer', 'painters', 'Position', [400 400 1000 800]);
% tiledlayout(2,2,'TileSpacing','compact');
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), (S_CBAR(:,:,i)/S_CBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
%     text(S_SDZ(:,1,i)*1.01, (S_CBAR(:,1,i)/S_CBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.0015 .1 -.05 8.8]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% title('Consumption AVG/SS','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), (S_NBAR(:,:,i)/S_NBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
%     text(S_SDZ(:,1,i)*1.01, (S_NBAR(:,1,i)/S_NBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.0015 .1 -.05 6.3]);
% %ytickformat('%.0f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% %legend(labels, 'Location','northwest','FontSize',fontS+2)
% title('Labor AVG/SS','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), (S_KBAR(:,:,i)/S_KBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
%     text(S_SDZ(:,1,i)*1.01, (S_KBAR(:,1,i)/S_KBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.0015 .1 -.1 19]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% title('Capital and investment AVG/SS','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), (S_YBAR(:,:,i)/S_YBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
%     text(S_SDZ(:,1,i)*1.01, (S_YBAR(:,1,i)/S_YBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.0015 .1 -.05 10.9]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% title('GDP AVG/SS','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% exportgraphics(gcf,"GRiskRBCepsilonGHH2M.eps","Resolution",300)
 


% figure;
% S_ZBAR=S_YBAR./(A*S_KBAR.^alpha.*S_NBAR.^(1-alpha));
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), (S_ZBAR(:,:,i)/S_ZBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
%     text(S_SDZ(:,1,i)*1.01, (S_ZBAR(:,1,i)/S_ZBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.0015 .1 -.005 1.05]);
% ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% title('TFP AVG/SS','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% exportgraphics(gcf,"GRiskRBCepsilonGHH2z.eps","Resolution",300)




% figure;
% hold on;
% for i=1:lsigmavect
%     plot(S_CSD(:,:,i), S_CBAR(:,:,i)-S_CBAR(:,lsdzvect,i), 'color',colors{i,1},'linewidth',1.5);
%     %text(S_SDZ(:,1,i)*1.01, S_CSD(:,1,i)./S_CBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.01 2 -.0005 .7]);
% ytickformat('%.1f')
% xlabel('SD','FontSize',fontS+2);
% ylabel('AVG','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% %legend(labels, 'Position', [.42 .2 .07 .3],'FontSize',fontS+2)
% title('Consumption AVG vs SD','Interpreter','Latex','FontSize',fontS+4);
% hold off;







% figure('Renderer', 'painters', 'Position', [10 10 1000 400]);
% tiledlayout(1,2,'TileSpacing','compact');
% nexttile;
% hold on;
% cssGainPercentVkss=nan(lsigmavect,lsdzvect);
% for i=1:lsigmavect
%     for j=1:lsdzvect
%         cssGainPercentVkss(i,j)=((((1-beta)*(1-sigmavect(i))*(S_V1(1,j,i)-S_V1(1,lsdzvect,i))+(cssTh-psi*nssTh^theta/theta)^(1-sigmavect(i)))^(1/(1-sigmavect(i)))+psi*nssTh^theta/theta)/cssTh-1)*100;
%     end
% end
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), cssGainPercentVkss(i,:), 'color',colors{i,1},'linewidth',1.5);
% end
% for i=[1 2 4:6]
%     text(S_SDZ(:,1,i)*1.01, cssGainPercentVkss(i,1), labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% i=3;
% text(S_SDZ(:,1,i)*1.01, cssGainPercentVkss(i,1)-.02, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% i=7;
% text(S_SDZ(:,1,i)*1.01, cssGainPercentVkss(i,1)+.05, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% axis([-.002 .1 -1 1.6]);
% ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% title('$x\%$ based on $v(k_{ss},E(z))$','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% cssGainPercentVkbar=nan(lsigmavect,lsdzvect);
% for i=1:lsigmavect
%     for j=1:lsdzvect
%         cssGainPercentVkbar(i,j)=((((1-beta)*(1-sigmavect(i))*(S_V3(1,j,i)-S_V3(1,lsdzvect,i))+(cssTh-psi*nssTh^theta/theta)^(1-sigmavect(i)))^(1/(1-sigmavect(i)))+psi*nssTh^theta/theta)/cssTh-1)*100;
%     end
% end
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), cssGainPercentVkbar(i,:), 'color',colors{i,1},'linewidth',1.5);
% end
% for i=[1 6]
%     text(S_SDZ(:,1,i)*1.01, cssGainPercentVkbar(i,1), labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% i=2;
% text(S_SDZ(:,1,i)*1.01, cssGainPercentVkbar(i,1)+.05, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% i=3;
% text(S_SDZ(:,1,i)*1.01, cssGainPercentVkbar(i,1)+.08, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% i=4;
% text(S_SDZ(:,1,i)*1.01, cssGainPercentVkbar(i,1)+.01, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% i=5;
% text(S_SDZ(:,1,i)*1.01, cssGainPercentVkbar(i,1)+.05, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% i=7;
% text(S_SDZ(:,1,i)*1.01, cssGainPercentVkbar(i,1)-.05, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% axis([-.001 .1 -.02 2.2]);
% ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% title('$x\%$ based on $v(\bar{k},E(z))$','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% exportgraphics(gcf,"GRiskRBCGHH2NfocFIGvksskbar.eps","Resolution",300)











% clearvars -except fontS;
% load GRiskGHH2RCNfoc_2024_04_15_11_23-8k51hp.mat
% 
% fontS=14;
% 
% figure('Renderer', 'painters', 'Position', [10 10 1000 400]);
% tiledlayout(1,2,'TileSpacing','compact');
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), S_CSDCOMPDATA(:,:,i), 'color',colors{i,1},'linewidth',1.5);
%     text(S_SDZ(:,1,i)*1.01, S_CSDCOMPDATA(:,1,i), labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% %text(.01,3.25, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% plot(S_SDZ(:,:,i), 1.3856*ones(lsdzvect),'color',[.5 .5 .5],'LineStyle',':');
% axis([-.0007 .1 -.05 4.5]);
% ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% %legend(labels, 'Location','southeast','FontSize',fontS+2)
% title('Consumption SD HP-filtered','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), S_NSDCOMPDATA(:,:,i), 'color',colors{i,1},'linewidth',1.5);
%     %text(S_SDZ(:,1,i)*1.01, S_NSDCOMPDATA(:,1,i), labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% plot(S_SDZ(:,:,i), 2.0873*ones(lsdzvect),'color',[.5 .5 .5],'LineStyle',':');
% axis([-.0007 .1 -.05 4.95]);
% ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% legend(labels, 'Location','northwest','FontSize',fontS+2)
% title('Labor SD HP-filtered','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% % nexttile;
% % hold on;
% % for i=1:lsigmavect
% %     plot(S_SDZ(:,:,i), S_ISDCOMPDATA(:,:,i), 'color',colors{i,1},'linewidth',1.5);
% %     text(S_SDZ(:,1,i)*1.01, S_ISDCOMPDATA(:,1,i), labels{i,1},'color',colors{i,1},'FontSize',fontS);
% % end
% % plot(S_SDZ(:,:,i), 7.1618*ones(lsdzvect),'color',[.5 .5 .5],'LineStyle',':');
% % axis([-.0007 .1 -.07 100]);
% % %ytickformat('%.1f')
% % xlabel('\sigma','FontSize',fontS+2);
% % fontsize(gca,fontS,"points")
% % centeraxes(gca);
% % legend(labels, 'Location','southeast','FontSize',fontS+2)
% % title('Investment SD HP-filtered','Interpreter','Latex','FontSize',fontS+4);
% % hold off;
% % % THIS ONE LOOKS WEIRD
% % 
% % 
% % nexttile;
% % hold on;
% % for i=1:lsigmavect
% %     plot(S_SDZ(:,:,i), S_YSDCOMPDATA(:,:,i), 'color',colors{i,1},'linewidth',1.5);
% %     %text(S_SDZ(:,1,i)*1.01, S_YSDCOMPDATA(:,1,i), labels{i,1},'color',colors{i,1},'FontSize',fontS);
% % end
% % plot(S_SDZ(:,:,i), 1.6443*ones(lsdzvect),'color',[.5 .5 .5],'LineStyle',':');
% % axis([-.0007 .1 -.07 8.6]);
% % %ytickformat('%.1f')
% % xlabel('\sigma','FontSize',fontS+2);
% % fontsize(gca,fontS,"points")
% % centeraxes(gca);
% % legend(labels, 'Location','southeast','FontSize',fontS+2)
% % title('GDP SD HP-filtered','Interpreter','Latex','FontSize',fontS+4);
% % hold off;
% 
% %exportgraphics(gcf,"GRiskRBCepsilonGHH2NfocFIGHP.eps","Resolution",300)







load GRiskGHH2RCNfoc_2025_02_15_20_32-8k51t;


figure('Renderer', 'painters', 'Position', [0 1000 625 800]);
tiledlayout(3,2,'TileSpacing','compact','Padding','compact');

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), S_CSD(:,:,i)./S_CBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
    %text(S_SDZ(:,1,i)*1.01, S_CSD(:,1,i)./S_CBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.001 .1 -.1 10.2]);
%ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
title('Consumption SD/AVG','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), S_NSD(:,:,i)./S_NBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
    %text(S_SDZ(:,1,i)*1.01, S_NSD(:,1,i)./S_NBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.001 .1 -.05 3.35]);
ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
title('Labor  SD/AVG','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), S_KSD(:,:,i)./S_KBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
    %text(S_SDZ(:,1,i)*1.01, S_KSD(:,1,i)./S_KBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.001 .1 -.2 19]);
%ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
title('Capital  SD/AVG','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), S_YSD(:,:,i)./S_YBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
    %text(S_SDZ(:,1,i)*1.01, S_YSD(:,1,i)./S_YBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.001 .1 -.15 15.75]);
%ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
title('GDP SD/AVG','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), S_ISD(:,:,i)./S_IBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
    %text(S_SDZ(:,1,i)*1.01, S_ISD(:,1,i)./S_IBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.001 .1 -.3 35]);
%ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
legend(labels, 'Position', [.6 .15 .1 .12],'FontSize',fontS+4)
title('Investment  SD/AVG','Interpreter','Latex','FontSize',fontS+4);
hold off;

exportgraphics(gcf,"GRiskRBCepsilonGHH2trSD.eps","Resolution",300)




% figure('Renderer', 'painters', 'Position', [400 400 1000 400]);
% tiledlayout(1,2,'TileSpacing','compact');
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), S_CSD(:,:,i)./S_CBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
%     %text(S_SDZ(:,1,i)*1.01, S_CSD(:,1,i)./S_CBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .1 -.1 9.9]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% legend(labels, 'Position', [.42 .2 .07 .3],'FontSize',fontS+2)
% title('Consumption SD/AVG','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), S_NSD(:,:,i)./S_NBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
%     %text(S_SDZ(:,1,i)*1.01, S_NSD(:,1,i)./S_NBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .1 -.05 3.3]);
% ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% %legend(labels, 'Location','northwest','FontSize',fontS+2)
% title('Labor  SD/AVG','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% exportgraphics(gcf,"GRiskRBCepsilonGHH2trSDcn.eps","Resolution",300)


% figure('Renderer', 'painters', 'Position', [400 400 1000 800]);
% tiledlayout(2,2,'TileSpacing','compact');
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), S_ISD(:,:,i)./S_IBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
%     %text(S_SDZ(:,1,i)*1.01, S_ISD(:,1,i)./S_IBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .1 -.3 36]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% %legend(labels, 'Location','southeast','FontSize',fontS+2)
% title('Investment  SD/AVG','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), S_KSD(:,:,i)./S_KBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
%     %text(S_SDZ(:,1,i)*1.01, S_KSD(:,1,i)./S_KBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .1 -.2 19]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% %legend(labels, 'Location','northwest','FontSize',fontS+2)
% title('Capital  SD/AVG','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), S_YSD(:,:,i)./S_YBAR(:,:,i)*100, 'color',colors{i,1},'linewidth',1.5);
%     %text(S_SDZ(:,1,i)*1.01, S_YSD(:,1,i)./S_YBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .1 -.15 16]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% legend(labels, 'Position', [.48 .35 .07 .15],'FontSize',fontS+2)
% title('GDP SD/AVG','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% exportgraphics(gcf,"GRiskRBCepsilonGHH2trSDiky.eps","Resolution",300)




figure('Renderer', 'painters', 'Position', [0 1000 625 800]);
tiledlayout(3,2,'TileSpacing','compact','Padding','compact');

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), (S_CBAR(:,:,i)/S_CBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
    text(S_SDZ(:,1,i)*1.01, (S_CBAR(:,1,i)/S_CBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.0015 .1 -.005 1.05]);
ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
title('Consumption AVG/SS','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), (S_NBAR(:,:,i)/S_NBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
    text(S_SDZ(:,1,i)*1.01, (S_NBAR(:,1,i)/S_NBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.0015 .1 -.11 .27]);
ytickformat('%.2f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
%legend(labels, 'Location','northwest','FontSize',fontS+2)
title('Labor AVG/SS','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), (S_KBAR(:,:,i)/S_KBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
    text(S_SDZ(:,1,i)*1.01, (S_KBAR(:,1,i)/S_KBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.0015 .1 -.05 6.6]);
%ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
title('Capital and investment AVG/SS','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile;
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), (S_YBAR(:,:,i)/S_YBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
    text(S_SDZ(:,1,i)*1.01, (S_YBAR(:,1,i)/S_YBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.0015 .1 -.02 2.4]);
ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
title('GDP AVG/SS','Interpreter','Latex','FontSize',fontS+4);
hold off;

nexttile
S_ZBAR=S_YBAR./(A*S_KBAR.^alpha.*S_NBAR.^(1-alpha));
hold on;
for i=1:lsigmavect
    plot(S_SDZ(:,:,i), (S_ZBAR(:,:,i)/S_ZBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
    text(S_SDZ(:,1,i)*1.01, (S_ZBAR(:,1,i)/S_ZBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
end
axis([-.0015 .1 -.005 .5]);
ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
legend(labels, 'Position', [.6 .15 .1 .12],'FontSize',fontS+4)
title('TFP AVG/SS','Interpreter','Latex','FontSize',fontS+4);
hold off;

exportgraphics(gcf,"GRiskRBCepsilonGHH2tM.eps","Resolution",300)





% figure('Renderer', 'painters', 'Position', [400 400 1000 800]);
% tiledlayout(2,2,'TileSpacing','compact');
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), (S_CBAR(:,:,i)/S_CBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
%     text(S_SDZ(:,1,i)*1.01, (S_CBAR(:,1,i)/S_CBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.0015 .1 -.005 1.05]);
% ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% title('Consumption AVG/SS','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), (S_NBAR(:,:,i)/S_NBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
%     text(S_SDZ(:,1,i)*1.01, (S_NBAR(:,1,i)/S_NBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.0015 .1 -.11 .27]);
% ytickformat('%.2f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% %legend(labels, 'Location','northwest','FontSize',fontS+2)
% title('Labor AVG/SS','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), (S_KBAR(:,:,i)/S_KBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
%     text(S_SDZ(:,1,i)*1.01, (S_KBAR(:,1,i)/S_KBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.0015 .1 -.05 6.6]);
% %ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% title('Capital and investment AVG/SS','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), (S_YBAR(:,:,i)/S_YBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
%     text(S_SDZ(:,1,i)*1.01, (S_YBAR(:,1,i)/S_YBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.0015 .1 -.02 2.5]);
% ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% title('GDP AVG/SS','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% exportgraphics(gcf,"GRiskRBCepsilonGHH2tM.eps","Resolution",300)



% figure;
% S_ZBAR=S_YBAR./(A*S_KBAR.^alpha.*S_NBAR.^(1-alpha));
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), (S_ZBAR(:,:,i)/S_ZBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
%     text(S_SDZ(:,1,i)*1.01, (S_ZBAR(:,1,i)/S_ZBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.0015 .1 -.005 .5]);
% ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% title('TFP AVG/SS','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% exportgraphics(gcf,"GRiskRBCepsilonGHH2tz.eps","Resolution",300)




% figure;
% hold on;
% for i=1:lsigmavect
%     plot(S_CSD(:,:,i), S_CBAR(:,:,i)-S_CBAR(:,lsdzvect,i), 'color',colors{i,1},'linewidth',1.5);
%     %text(S_SDZ(:,1,i)*1.01, S_CSD(:,1,i)./S_CBAR(:,1,i)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.01 2 -.0005 .7]);
% ytickformat('%.1f')
% xlabel('SD','FontSize',fontS+2);
% ylabel('AVG','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% %legend(labels, 'Position', [.42 .2 .07 .3],'FontSize',fontS+2)
% title('Consumption AVG vs SD','Interpreter','Latex','FontSize',fontS+4);
% hold off;
